name = "server-selector"
main = "index.js"
compatibility_date = "2025-10-30"

[[kv_namespaces]]
binding = "VISITED_KV"
id = "0fe81a9ee13f4bad87d2ad4706409a5a"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
